# Generated by Django 3.0.3 on 2020-03-05 04:20

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('intprop', models.IntegerField(primary_key='True', serialize=False)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('st', models.CharField(max_length=2)),
                ('postalcode', models.IntegerField()),
                ('ftruckrental', models.IntegerField()),
                ('ftruckrentalss', models.IntegerField()),
                ('fdisplay', models.CharField(max_length=200)),
                ('fltInStorePerc', models.DecimalField(decimal_places=1, max_digits=2)),
                ('facq', models.CharField(max_length=200)),
                ('community', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strUnitType', models.CharField(max_length=5)),
                ('strInside', models.CharField(max_length=1)),
                ('dblfloor', models.IntegerField()),
                ('fltInStorePerc', models.DecimalField(decimal_places=1, max_digits=2)),
                ('dblcurrentrate', models.IntegerField()),
                ('dblttlSpaces', models.IntegerField()),
                ('dblTtlAvail', models.IntegerField()),
                ('fineSizeCategory', models.CharField(max_length=200)),
                ('broadSizeCategory', models.CharField(max_length=200)),
                ('strSpecial', models.CharField(max_length=1)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Store')),
            ],
        ),
    ]
