# Generated by Django 3.0.3 on 2020-03-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeinventory',
            old_name='store',
            new_name='intprop',
        ),
    ]
