# Generated by Django 3.0.3 on 2020-03-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200304_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinventory',
            options={'ordering': ['dblcurrentrate']},
        ),
    ]
